## mini-batch原理
- mini-batch就是并行处理多个图，这里把多个图的邻接矩阵A1、A2、……拼接成一个大的矩阵，可以看作一个对角矩阵（出现了很多0元素，即稀疏矩阵的存储）
- https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html?highlight=PairData#pairs-of-graphs
- https://blog.csdn.net/qq_38432089/article/details/122317699

In [28]:
import torch
from torch_geometric.loader import DataLoader
from torch_geometric.data import Data

edge_index_s = torch.tensor([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
])
x = torch.randn(5, 2)  # 5 nodes.
edge_weight = torch.tensor(
    [0.1, 0.2, 0.3, 0.4])
data=Data(x=x, edge_index=edge_index_s,edge_weight=edge_weight)

data_list = [data, data]
loader1 = DataLoader(data_list, batch_size=1)
loader2 = DataLoader(data_list, batch_size=2)
i=0
for batch in loader1:
    print(i)
    i+=1
    print(batch)
    print(batch.edge_index)
    print(batch.edge_weight)
i=0
for batch in loader2:
    print(i)
    i+=1
    print(batch)
    print(batch.edge_index)
    print(batch.edge_weight)
    print(batch.x)

0
DataBatch(x=[5, 2], edge_index=[2, 4], edge_weight=[4], batch=[5], ptr=[2])
tensor([[0, 0, 0, 0],
        [1, 2, 3, 4]])
tensor([0.1000, 0.2000, 0.3000, 0.4000])
1
DataBatch(x=[5, 2], edge_index=[2, 4], edge_weight=[4], batch=[5], ptr=[2])
tensor([[0, 0, 0, 0],
        [1, 2, 3, 4]])
tensor([0.1000, 0.2000, 0.3000, 0.4000])
0
DataBatch(x=[10, 2], edge_index=[2, 8], edge_weight=[8], batch=[10], ptr=[3])
tensor([[0, 0, 0, 0, 5, 5, 5, 5],
        [1, 2, 3, 4, 6, 7, 8, 9]])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.1000, 0.2000, 0.3000, 0.4000])
tensor([[-1.1419, -0.3925],
        [-1.9028, -0.0072],
        [-1.0383, -0.5071],
        [ 0.6624, -0.3816],
        [ 1.1719,  1.1952],
        [-1.1419, -0.3925],
        [-1.9028, -0.0072],
        [-1.0383, -0.5071],
        [ 0.6624, -0.3816],
        [ 1.1719,  1.1952]])


- 要组成batch的用for循环构建datalist

In [36]:
x = torch.tensor([[[-1.1419, -0.3925],
        [-1.9028, -0.0072],
        [-1.0383, -0.5071],
        [ 0.6624, -0.3816],
        [ 1.1719,  1.1952]],[
        [-1.1419, -0.3925],
        [-1.9028, -0.0072],
        [-1.0383, -0.5071],
        [ 0.6624, -0.3816],
        [ 1.1719,  1.1952]]])
x.shape
edge_index=torch.tensor([[0, 0, 0, 0],[1, 2, 3, 4]])
edge_index.shape
datalist=[]
for i in range(x.shape[0]):
        datalist.append(Data(x=x[i], edge_index=edge_index))
loader = DataLoader(datalist, batch_size=1)
for batch in loader:
    print(i)
    i+=1
    print(batch)
    print(batch.edge_index)
    print(batch.x)

1
DataBatch(x=[5, 2], edge_index=[2, 4], batch=[5], ptr=[2])
tensor([[0, 0, 0, 0],
        [1, 2, 3, 4]])
tensor([[-1.1419, -0.3925],
        [-1.9028, -0.0072],
        [-1.0383, -0.5071],
        [ 0.6624, -0.3816],
        [ 1.1719,  1.1952]])
2
DataBatch(x=[5, 2], edge_index=[2, 4], batch=[5], ptr=[2])
tensor([[0, 0, 0, 0],
        [1, 2, 3, 4]])
tensor([[-1.1419, -0.3925],
        [-1.9028, -0.0072],
        [-1.0383, -0.5071],
        [ 0.6624, -0.3816],
        [ 1.1719,  1.1952]])
